### ISSUE TITLE
Learning Path 11-01: Deploy a model to a managed online endpoint Issue

### ISSUE THREAD

**Issue by SkillableKA** [MicrosoftLearning/mslearn-azure-ml#106]
Task: Deploy a model to an online endpoint
Step 1.) Open the Labs/11/Deploy to online endpoint.ipynb notebook.

Description of issue:

When running the code inside the notebook, the ml_client.begin_create_or_update(endpoint).result() command fails [P1]. The error states it is missing a resource provider but does not specify which resource provider is missing [P2]. In my testing I have systematically registered all of the AI service resource providers one at a time and retested, but still unable to proceed [P3].

https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-services-resource-providers

[P1]
![image](https://github.com/user-attachments/assets/6f1bb8a3-40f6-4e12-a3a9-17a503589c39)

[P2]
![image](https://github.com/user-attachments/assets/2fa3046c-b14a-4438-869a-6adfa414566e)

[P3]
![image](https://github.com/user-attachments/assets/1238d63e-5dc6-4c32-a6a7-d113b504a6d4)

**Comment by afelix-95** [comment]
Thank you for pointing that out! We're aware of the issue and currently working with Skillable's support team to fix it.

**Comment by afelix-95** [comment]
There were additional resource providers required to deploy the endpoint. They are now being pre-registered in the VM's environment and were also added to the setup.sh file in this repo. Issue should be fixed now.
