### ISSUE TITLE
Hyperparameter tuning :  Training script command job runs indefinitely

### ISSUE THREAD

**Issue by o-rod** [MicrosoftLearning/mslearn-azure-ml#13]
# Module: Perform hyperparameter tuning with Azure Machine Learning
#### Step: Configure and run a command job in Hyperparameter tuning.ipynb

Description of issue
Commnad job runs indefinitely - remains in Preparing status, does not transition to running status, nor complete status

Repro steps:

1.  perform all steps given here: https://microsoftlearning.github.io/mslearn-azure-ml/Instructions/09-Hyperparameter-tuning.html
2.  Issue will be encountered in the following section of notebook Configure and run a command job, prior to defining sweep and running sweep job.

**Comment by JisenRen** [comment]
I also get stuck in this notebook. The compute cluster never scales up even if the sweep job is submitted.

**Comment by o-rod** [comment]
Hi, 

I re-ran the notebook successfully.  The train job ran for about 5 min and the sweep job ran for about 10 min. 
This issue should be closed. 

Thanks,
orod
