### ISSUE TITLE
LAB 11:  Deploy to Batch Endpoint - JSONDecodeError

### ISSUE THREAD

**Issue by o-rod** [MicrosoftLearning/mslearn-azure-ml#14]
# Module: Deploy To Batch Endpoint
#### Step: Submit the Job after defining the input

Description of issue
Receiving a JSONDecodeError upon submitting the job in the notebook
Repro steps:

1.  Follow all the steps in the notebook 
2.  Error thrown in the second step [submit job] just after defining the input for the data asset

stack trace given below
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/ai/ml/_utils/_endpoint_utils.py:116, in validate_response(response)
    115 try:
--> 116     r_json = response.json()
    117 except ValueError:
    118     # exception is not in the json format

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/core/rest/_http_response_impl.py:299, in _HttpResponseBaseImpl.json(self)
    298 if not self._json:
--> 299     self._json = loads(self.text())
    300 return self._json

File /anaconda/envs/azureml_py38/lib/python3.8/json/__init__.py:357, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    354 if (cls is None and object_hook is None and
    355         parse_int is None and parse_float is None and
    356         parse_constant is None and object_pairs_hook is None and not kw):
--> 357     return _default_decoder.decode(s)
    358 if cls is None:

File /anaconda/envs/azureml_py38/lib/python3.8/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File /anaconda/envs/azureml_py38/lib/python3.8/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
Cell In[17], line 1
----> 1 job = ml_client.batch_endpoints.invoke(
      2     endpoint_name=endpoint.name, 
      3     input=input)
      5 ml_client.jobs.get(job.name)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/core/tracing/decorator.py:78, in distributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer(*args, **kwargs)
     76 span_impl_type = settings.tracing_implementation()
     77 if span_impl_type is None:
---> 78     return func(*args, **kwargs)
     80 # Merge span is parameter is set, but only if no explicit parent are passed
     81 if merge_span and not passed_in_parent:

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/ai/ml/_telemetry/activity.py:263, in monitor_with_activity.<locals>.monitor.<locals>.wrapper(*args, **kwargs)
    260 @functools.wraps(f)
    261 def wrapper(*args, **kwargs):
    262     with log_activity(logger, activity_name or f.__name__, activity_type, custom_dimensions):
--> 263         return f(*args, **kwargs)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/ai/ml/operations/_batch_endpoint_operations.py:316, in BatchEndpointOperations.invoke(self, endpoint_name, deployment_name, inputs, **kwargs)
    309     headers[EndpointInvokeFields.MODEL_DEPLOYMENT] = deployment_name
    311 response = self._requests_pipeline.post(
    312     endpoint.properties.scoring_uri,
    313     json=BatchJobResource(properties=batch_job).serialize(),
    314     headers=headers,
    315 )
--> 316 validate_response(response)
    317 batch_job = json.loads(response.text())
    318 return BatchJobResource.deserialize(batch_job)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/ai/ml/_utils/_endpoint_utils.py:119, in validate_response(response)
    116         r_json = response.json()
    117     except ValueError:
    118         # exception is not in the json format
--> 119         raise Exception(response.content.decode("utf-8"))
    120 failure_msg = r_json.get("error", {}).get("message", response)
    121 error_map = {
    122     401: ClientAuthenticationError,
    123     404: ResourceNotFoundError,
    124     409: ResourceExistsError,
    125 }

Exception: BY_POLICY

**Comment by iamramengirl** [comment]
Lab 11 appears to have worked successfully. I used the Python 3.10 Kernel.

**Comment by Mihai-Ac** [comment]
Hello,

Ran through the notebook, following all instructions and encountered no errors. Please make sure you wait between the creation of the endpoint and deployment to avoid similar issues.

**Comment by o-rod** [comment]
> Hello,
> 
> Ran through the notebook, following all instructions and encountered no errors. Please make sure you wait between the creation of the endpoint and deployment to avoid similar issues.

Hi, 
Still getting the same JSONDecodeError w same steps.  Same error using Python 3.10 Kernel as well.
Would you be so kind as to provide the  evidence [as I have done above] that you've successfully ran all the steps in the notebook for Lab 11.
Thanks.

**Comment by Mihai-Ac** [comment]
Hello @o-rod 
I ran the lab again and still couldn´t reproduce the error.
Here is the screenshot with the notebook with the submitted job cell 
![image](https://github.com/MicrosoftLearning/mslearn-azure-ml/assets/110993710/f09e21fc-e6fd-4dc0-9fb9-94eec3a55f49)
 and the screenshot with the successful deployment of the batch run :
 
![image](https://github.com/MicrosoftLearning/mslearn-azure-ml/assets/110993710/086230af-e9ff-480d-8fb1-d04cf4cfd375)
 
I also made sure that the endpoint was successfully deployed before submitting the job:
![image](https://github.com/MicrosoftLearning/mslearn-azure-ml/assets/110993710/06c3dc76-9a13-4369-9324-46c6bf28681d)
