### ISSUE TITLE
list_experiments() method has been replaced by search_experiments()

### ISSUE THREAD

**Issue by GildardoRojas** [MicrosoftLearning/mslearn-azure-ml#16]
# Module: 08
#### Step: Notebook: Use MLFlow to view and search for experiments

Description of issue: Method list_expermients() is deprecated, it fails execution as it is now in the notebook. 
Solution: Replace with search_experiments() method.
Repro steps: Execute Cell 15

1.
1.
1.

**Comment by madiepev** [comment]
Thank you for submitting the issue. The code has been fixed
