### ISSUE TITLE
Minor lab instruction change

### ISSUE THREAD

**Issue by davecatt** [MicrosoftLearning/mslearn-azure-ml#19]
# Module: 01
#### Step: 09

Description of issue
The line is "Note the Manage section, which includes Compute and Datastores among other things. These are infrastructural resources needed to train or deploy a machine learning model."

However datastores are not under Manage anymore.  One of my students got confused at this.
Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
Thanks. Updated the instructions
