### ISSUE TITLE
Error on lab 5 instructions

### ISSUE THREAD

**Issue by davecatt** [MicrosoftLearning/mslearn-azure-ml#20]
# Module: 05 AML designer
#### Step: 08

Description of issue
"Drag and drop the Train a Decision Tree Classifier Model component on to the canvas, below the Remove empty rows."

Should be 

"Drag and drop the Train a Decision Tree Classifier Model component on to the canvas, below the Normalize numerical columns."

Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
Thank you for submitting the issue. Typo has been fixed
