### ISSUE TITLE
Lab 5 no Metrics output

### ISSUE THREAD

**Issue by Derekp20** [MicrosoftLearning/mslearn-azure-ml#21]
# Module: 05
#### Step: 6

No metrics appear to look at.

Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
Thank you for creating an issue. The metrics appear when you select the train model component in the completed pipeline run: 
<img width="737" alt="image" src="https://github.com/MicrosoftLearning/mslearn-azure-ml/assets/48012580/f56a6646-3912-4975-8084-07489ad55395">
