### ISSUE TITLE
Module 2 Metrics not shown

### ISSUE THREAD

**Issue by cyapur** [MicrosoftLearning/mslearn-azure-ml#24]
# Module: 02
#### Step: 04

Link: https://github.com/MicrosoftLearning/mslearn-azure-ml/blob/main/Instructions/02-Explore-developer-tools.md

Description of issue: The instruction says:

> When the job is completed, you can find the AUC and Accuracy of the model under Metrics.

There is no AUC either Accuracy of the model under Metrics.

Repro steps:

1. Just followed the instructions, the job ran successfully.

![image](https://github.com/MicrosoftLearning/mslearn-azure-ml/assets/37354517/77bde64d-75fd-48c6-a3bf-a1434b441f1d)

**Comment by madiepev** [comment]
Thank you for reporting this. Fixed the instructions
