### ISSUE TITLE
Wrong example in Module of Lab 09

### ISSUE THREAD

**Issue by cyapur** [MicrosoftLearning/mslearn-azure-ml#26]
# Module: Perform hyperparameter tuning with Azure Machine Learning
## Lab/Demo: 09

Description of issue: An example of the instructions is misleading. It says:

> The following search space [..] `learning_rate` hyperparameter can have any value from a **normal distribution with a mean of 10 and standard deviation of 3**

However, the code clearly specifies a **Uniform distribution with range [0.05, 0.1]**

Both statements are underlined in red in the image below, and the link to that exact site: https://learn.microsoft.com/en-us/training/modules/perform-hyperparameter-tuning-azure-machine-learning-pipelines/2-define-search-space

![image](https://github.com/MicrosoftLearning/mslearn-azure-ml/assets/37354517/259d8905-59d7-432a-bb84-d670c1cf8883)

**Comment by madiepev** [comment]
Thanks for reporting this. The change has been implemented and will be published soon. For future feedback related to Learn content, you can use the option for "reporting an issue" at the bottom of the page.
