### ISSUE TITLE
LAB 11 - Deploy to an online endpoint - Model is not deploying

### ISSUE THREAD

**Issue by anglael** [MicrosoftLearning/mslearn-azure-ml#30]
Lab/Demo: 11

Step: 7 - Create the deployment

Description of issue: Create the deployment step fails with the following error 

HttpResponseError: (BadRequest) The request is invalid. Code: BadRequest Message: The request is invalid. Exception Details: (InferencingClientCreateDeploymentFailed) InferencingClient HttpRequest error, error detail: {"errors":{"VmSize":["Not enough quota available for Standard_F4s_v2 in SubscriptionId a7842ee4-aaba-4d38-8bba-c1804e31a761. Current usage/limit: 0/6. Additional needed: 8 Please see troubleshooting guide, available here: https://aka.ms/oe-tsg#error-outofquota"]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-a95a95afd7040aa9217f2d51d95c71c1-894d1cf3aba15e15-01"} Code: InferencingClientCreateDeploymentFailed Message: InferencingClient HttpRequest error, error detail: {"errors":{"VmSize":["Not enough quota available for Standard_F4s_v2 in SubscriptionId a7842ee4-aaba-4d38-8bba-c1804e31a761. Current usage/limit: 0/6. Additional needed: 8 Please see troubleshooting guide, available here: https://aka.ms/oe-tsg#error-outofquota"]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-a95a95afd7040aa9217f2d51d95c71c1-894d1cf3aba15e15-01"} Additional Information:Type: ComponentName Info: { "value": "managementfrontend" }Type: Correlation Info: { "value": { "operation": "a95a95afd7040aa9217f2d51d95c71c1", "request": "d04106a72eecc04b" } }Type: Environment Info: { "value": "northeurope" }Type: Location Info: { "value": "northeurope" }Type: Time Info: { "value": "2023-06-25T08:14:02.4646535+00:00" }

Repro steps:

1. Run the notebook as described on https://microsoftlearning.github.io/mslearn-azure-ml/Instructions/11-Deploy-online-endpoint.html

**Fix:** I have changed the instance type to Standard_E4s_v3 in previous step "Configure the deployment" 
    instance_type="Standard_E4s_v3"

Thanks!

**Comment by madiepev** [comment]
Thanks for reporting this issue. The available quota depends on the subscription used for the exercises. We'll therefore not change this in the content.
