### ISSUE TITLE
LAB 10 - Build the pipeline to create the responsible AI dashboard - Requires additional info 

### ISSUE THREAD

**Issue by anglael** [MicrosoftLearning/mslearn-azure-ml#31]
Lab/Demo: 10
Task: Build the pipeline to create the responsible AI dashboard
Steps: 5 and 6

Description of issue: it's not obvious that before running the cell the values for "subscription_id" and "resource_group_name" should be replaced with current ones 

Repro steps:

1. Run all cells in the notebook "Labs/10/Create Responsible AI dashboard.ipynb"
2. On the step "Build the pipeline to create the responsible AI dashboard" you'll get an error:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[9], line 5
      1 # Get handle to azureml registry for the RAI built in components
      2 registry_name = "azureml"
      3 ml_client_registry = MLClient(
      4     credential=credential,
----> 5     subscription_id=subscription_id,
      6     resource_group_name=resource_group,
      7     registry_name=registry_name,
      8 )
      9 print(ml_client_registry)

NameError: name 'subscription_id' is not defined

FIX: Click on subscription tile on the right top corner and copy/paste appropriate values for subscription_id and resource_group_name with quotes.

Thanks!

**Comment by madiepev** [comment]
Thank you for raising this issue. I fixed it by making it retrieve the sub id and resource group name from the ml_client.
