### ISSUE TITLE
Instruction needs to be modified

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/mslearn-azure-ml#32]
# Module: 3
#### Step: 1

Description of issue
It says "In the Azure portal, navigate to the new resource group named rg-dp100-labs."
However learners found that there is no resource group named "rg-dp100-labs. Rather the name of the resource group created starts with "rg-dp100". So the instruction should be like this:

"In the Azure portal, navigate to the new resource group that starts with "rg-dp100" ."
  
<img width="791" alt="image" src="https://github.com/MicrosoftLearning/mslearn-azure-ml/assets/58412718/2c0e57d4-6a4c-4a6c-8db3-b88c79bcb6c3">

Repro steps:

1. Run the setup file cloned from git clone https://github.com/MicrosoftLearning/mslearn-azure-ml.git azure-ml-labs
1. Go to the resource groups in portal.
1.

**Comment by Jason-Microsoft-MTT** [comment]
I havent noticed a fix for this issue - the instructions in the labs still refer to rg-dp-100-labs and nit a unique identifier

**Comment by madiepev** [comment]
Issue has been fixed
