### ISSUE TITLE
Error Messages in Lab 2 - Explore developer tools for workspace interaction

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/mslearn-azure-ml#34]
# Module: 02-Explore developer tools for workspace interaction
#### Step: 02

Description of issue
Not sure if this is a true issue, or if the lab instructions should be updated about these warning.

Repro steps:

The code block says to open a terminal and run these commands:
` pip uninstall azure-ai-ml
 pip install azure-ai-ml`

The first statement about uninstall... The instructions say to Ignore any error messages that say that packages were not installed.  My concern is the 2nd statement which installs the package.

There are 3 red warnings that come up:
`ERROR: azure-storage-file-share 12.13.0 has requirement azure-core<2.0.0,>=1.28.0, but you'll have azure-core 1.26.4 which is incompatible. 
ERROR: azure-storage-file-datalake 12.12.0 has requirement azure-core<2.0.0,>=1.28.0, but you'll have azure-core 1.26.4 which is incompatible.
ERROR: azure-storage-file-datalake 12.12.0 has requirement azure-storage-blob<13.0.0,>=12.17.0, but you'll have azure-storage-blob 12.13.0 which is incompatible.`

I don't know if these are issues that need to be fixed, or if they are ok; However -- my opinion -- the lab instructions should be modified to something like "you can ignore any error messages about azure-storage that appear" or something like that.

The lab *does* complete successfully.

**Comment by madiepev** [comment]
Thank you for submitting an issue. Since the error messages differ based on the SDK installed we won't be updating the instructions accordingly. Mentioning that error messages are to be expected should be sufficient.
