### ISSUE TITLE
Instructions need updated to reflect UI change for running a Designer pipeline

### ISSUE THREAD

**Issue by Jason-Microsoft-MTT** [MicrosoftLearning/mslearn-azure-ml#37]
# Module: 02
#### Step: All

Description of issue
The UI has been updated along with the Designer Pipeline Interface - there is no longer a Settings button where the instructions state they are and the compute is now defined when you use the "Configure and Submit" button. The instructions need modified to reflect the changes.

<img width="461" alt="image" src="https://github.com/MicrosoftLearning/mslearn-azure-ml/assets/120508481/21fd9745-5d33-42f4-9e32-00e4eda23f78">

Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
Thank you for submitting an issue. The instructions have been updated.
