### ISSUE TITLE
Cannot Export As - UI Issue

### ISSUE THREAD

**Issue by Jason-Microsoft-MTT** [MicrosoftLearning/mslearn-azure-ml#38]
# Module: 08
#### Step: 05

Description of issue
When selecting Export As -> Python (.py) option - nothing happens. I believe there is a UI issue that isnt creating a file. Two learners brought up the issue and have reproduced it myself.

Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
Thank you for submitting an issue. If nothing happens it sounds like a bug in the UI. The instructions are still correct and should work as expected when the product performs as expected.
