### ISSUE TITLE
Explore the Azure Machine Learning workspace

### ISSUE THREAD

**Issue by naveen1973** [MicrosoftLearning/mslearn-azure-ml#40]
# Module: 00
#### Step: 3

https://microsoftlearning.github.io/mslearn-azure-ml/Instructions/02-Explore-Azure-Machine-Learning.html

Description of issue
Should compute target not be created first? There is no "Submit"-button. Do they mean "Submit + Review"

After this step this are also very clear
Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
Thank you for submitting an issue. Instructions have been updated.
