### ISSUE TITLE
Lab 11: "Create the deployment" cell fails ResourceNotReady, container killed after pip error

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/mslearn-azure-ml#41]
- Lab 11: Deploy a model to a managed online endpoint
- Task: Deploy a model to an online endpoint
- Step 3: Run all cells in the notebook.
- 7th cell of notebook: `ml_client.online_deployments.begin_create_or_update(blue_deployment).result()`

When running the above-referenced notebook cell per the corresponding lab instruction, the model cannot be deployed. The cell fails with an error message summary beginning with:

```
HttpResponseError: (None) ResourceNotReady: User container has crashed or terminated: Liveness probe failed: HTTP probe failed with statuscode: 502.
```

The endpoint was successfully created before running the above-referenced deployment cell, as specified by the text of the notebook.

The full error output displayed in the notebook is attached here: [notebook-error.txt](https://github.com/MicrosoftLearning/mslearn-azure-ml/files/12442362/az400-notebook-error.txt)

Inspecting the logs on the endpoint page (attached: [deployment-log.txt](https://github.com/MicrosoftLearning/mslearn-azure-ml/files/12442367/az400-deployment-log.txt)), we can see that the container was killed after an error was thrown in the setup process.

```
Pip subprocess error:
ERROR: Package 'setuptools' requires a different Python: 3.7.13 not in '>=3.8'
```

```
CondaEnvException: Pip failed

Error occurred. Sleeping to send error logs.
2023-08-25T16:33:29,175665415+00:00 - gunicorn/finish 95 0
2023-08-25T16:33:29,177580424+00:00 - Exit code 95 is not normal. Killing image.
```

This also is likely to affect the `Deploy to batch endpoint.ipynb` notebook in Lab "Deploy a model to a batch endpoint", as it uses the same model files.

**Comment by madiepev** [comment]
Thank you for submitting an issue. We're actively investigating the issue.

**Comment by madiepev** [comment]
Issue has been fixed in latest PR by updating the cloudpickle version. Let us know if the problem still persists!
