### ISSUE TITLE
[Update] From azure ml sdk version 1 to version 2

### ISSUE THREAD

**Issue by mahimairaja** [MicrosoftLearning/mslearn-azure-ml#53]
I find the sample notebooks provided in the ms learn repo is much helpful.
In the notebooks from [mslearn-dp-100](https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/04%20-%20Run%20Experiments.ipynb) I could see that some of the code is in version 1 - like using ScriptRunConfig is used from V1 instead of Command, it would be great if it is updated according to version 2. 

I would love to contribute, Thank you!!!

**Comment by madiepev** [comment]
This repo is the updated version of the content in the mslearn-dp-100 repo. It's not 1:1 the same because the SDK works a bit differently in v2. Is there something specific that you are missing in this repo compared to the previous?
