### ISSUE TITLE
Unable to Run Lab/03/Work with data.ipynb completely

### ISSUE THREAD

**Issue by jzm0144** [MicrosoftLearning/mslearn-azure-ml#59]
# Module: 00
#### Step: 00

Description of issue: Cannot run the section to read the registered_data_asset using the mltable. I also tried to see what the latest ui of ml studio offers to read. I found this example code, this also won't work.

data_asset = ml_client.data.get("diabetes", version="1")

df = pd.read_csv(data_asset.path)
df

It seems like the mltable is just no installable on Mac M1 machines, neither is azureml-fsspec (which is end of day dependent of dotnetcore2 somehow).

Looking for help, this is import ant for my project.

Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
Thank you for submitting an issue. The notebook should be run in the Azure Machine Learning workspace using the compute instance. Please follow the instructions as they're stated exactly to avoid these issues.
