### ISSUE TITLE
Error loading data, in Lab06 

### ISSUE THREAD

**Issue by tottokug** [MicrosoftLearning/mslearn-azure-ml#75]
# Module: 5
#### Step: 00

Description of issue
In setup.sh, when creating data assets, diabetes-data/MLTABLE and orange-juice-data/MLTABLE are incorrectly set.

```

paths:
  - files: ./*.csv
  
```

but
this causes the data assets to fail to load.

```
paths:
  - files: ./diabetes.csv
```

This can be solved by setting the paths: files .
Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
Thanks! Issue should be fixed now.
