### ISSUE TITLE
typo in the instruction section

### ISSUE THREAD

**Issue by IanniMuliterno** [MicrosoftLearning/mslearn-azure-ml#76]
# Module: 02
## instructions section

Description of issue

There's a small typo [here](https://microsoftlearning.github.io/mslearn-azure-ml/Instructions/02-Explore-Azure-Machine-Learning.html),
in the **Author a training pipeline** topic, step 6, it is written :

"On the Runtime settings page an error appears as you don´t a default compute to run the pipeline."

It should be corrected to:

"On the Runtime settings page an error appears as you don´t **have a** default compute to run the pipeline."

**Comment by madiepev** [comment]
Thanks! Issue fixed with latest PR.
