### ISSUE TITLE
Trying to import non-existing class `RandomParameterSampling` from `azure.ai.ml.sweep`. It should be `RandomSamplingAlgorithm`

### ISSUE THREAD

**Issue by carlosjuribe** [MicrosoftLearning/mslearn-azure-ml#78]
# Module: Perform hyperparameter tuning with Azure Machine Learning
#### Subsection: Sobol

In the section [Configure a sampling method](https://learn.microsoft.com/en-us/training/modules/perform-hyperparameter-tuning-azure-machine-learning-pipelines/3-configure-sampling-method) of the module "Perform hyperparameter tuning with Azure Machine Learning" there is one Python line that does not work because it's trying to import a class (`RandomParameterSampling`) that no longer exists.

![image](https://github.com/MicrosoftLearning/mslearn-azure-ml/assets/46844109/757ae0dd-ad59-463b-8e81-acf3a62e027b)

- **Kernel**: `Python 3.10 - SDK v2`
- **Library version**: Latest version (`1.15.0`) of `azure.ai.ml`.

The import statement:

```python
from azure.ai.ml.sweep import RandomParameterSampling
```
produces the error:

```python
ImportError: cannot import name 'RandomParameterSampling' from 'azure.ai.ml.sweep' (/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azure/ai/ml/sweep/__init__.py)
```

The class to import should be `RandomSamplingAlgorithm`:

```python
from azure.ai.ml.sweep import RandomSamplingAlgorithm
```

Evidence:

![image](https://github.com/MicrosoftLearning/mslearn-azure-ml/assets/46844109/ccad0b34-fd11-45cc-8b8f-79ce4fa50506)

**Comment by madiepev** [comment]
Thanks for reporting this. I'm assuming this is related to the Learn content. Just FYI that you can also submit feedback through the website (scroll down to the bottom of the page). I changed the Learn content and the changes should go live this week.
