### ISSUE TITLE
Job Failed due to change needed in Dataset MLTable .yml file

### ISSUE THREAD

**Issue by kavsrd13** [MicrosoftLearning/mslearn-azure-ml#83]
# Module: 03
#### Step: 06

Description of issue
While creating MLTable data asset through MLTable .yml file ,path mentioned is 
1) paths:
  - file: ./*.csv
 which is not correct

Repro steps:

1.Changes needed in Orange Juice dataset MLTable yml file
paths:
  - file: ./orange-juice-data.csv
 
Similary change needed in Diabetes MLTable .yml file
paths:
  - file: ./diabetes-data.csv

**Comment by madiepev** [comment]
Thanks! Issue is fixed now.
