### ISSUE TITLE
Typo Understanding

### ISSUE THREAD

**Issue by raduhackit** [MicrosoftLearning/mslearn-azure-ml#88]
# Module: 04
#### Step: 00

Description of issue

In the text it says:
"Currently, your compute cluster aml-cluster can only scale do a maximum of one node ..."
However the aml-cluster was create prior with:

        # Nodes in cluster
        max_instances=2,

In the initial code it should be:

        # Nodes in cluster
        max_instances=1,

After which the aml-cluster is updated to max_instances=2

<img width="881" alt="Screenshot 2024-05-22 125343" src="https://github.com/MicrosoftLearning/mslearn-azure-ml/assets/96863126/03f94db0-afc8-4685-8286-1cb2a1ddc382">

Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
Thanks for reporting this. Issue has been fixed
