### ISSUE TITLE
Changes in workflow and UI when setting up CloudShell

### ISSUE THREAD

**Issue by MSFT-mengchong** [MicrosoftLearning/mslearn-azure-ml#94]
# Module: 02
#### Step: 04

Description of issue - The UI and workflow of setting up the Azure CloudShell have changed.

Repro steps:

0. This is how the UI looks like now when starting Azure CloudShell
![image](https://github.com/user-attachments/assets/6034b1fb-460b-414d-bc25-4f60f23bdd7d)

1. The attached screenshot is the default settings after selecting either Azure CLI or PowerShell option.
![image](https://github.com/user-attachments/assets/1d2efee3-bc07-4ac7-a816-414ed38ae4ee)

2. This screenshot shows the required selections.
![image](https://github.com/user-attachments/assets/63ea0c14-c116-4f9d-b269-6f809e7e6066)

3. This screenshot shows the 2nd selection (We will create a storage account for you) being picked.
![image](https://github.com/user-attachments/assets/e9efc0c9-3e9f-4956-aaea-7b35851e3343)

4.  This screenshot shows the Azure CloudShell setup progress, it is the same regardless of Azure CLI or Cloudshell.
![image](https://github.com/user-attachments/assets/e7d7e63a-22c1-4a6f-b3ed-d53861f46bf5)

When successfully completed the UI will present either the Azure CLI or PowerShell as selected in Step 0.

**Comment by afelix-95** [comment]
Thanks for pointing it out! In fact, for the purpose of the lab exercises, a storage account is not required (that wasn't an option before). The instructions were updated to reflect that change.
