### ISSUE TITLE
Lab 10: Error when running last step of the jupyter notebooks: Run the Log models with MLFlow.ipynb

### ISSUE THREAD

**Issue by jarougha** [MicrosoftLearning/mslearn-azure-ml#98]
# Module: Register a MLFlow model in Azure Machine Learning
#### Step: Lab 10: Log models with MLFlow.ipynb
![image](https://github.com/user-attachments/assets/ecc7b143-093e-4381-85fd-a1d86572e3af)

Description of issue
**Lab 10: (Last Cell run even, waited till all other jobs complete in AML before running this last step)**
![image](https://github.com/user-attachments/assets/6e1d4910-43eb-4b51-bf70-48f0d9380e3a)
![image](https://github.com/user-attachments/assets/b2ce525d-9c00-4665-9583-b94d97da268e)
**Debug: Printed path for model:** azureml://jobs/cool_beard_rsghphcch0/outputs/artifacts/paths/model/

**Potential WorkAround**
Assign job_name, the constructed name in the diabetes-train-autolog job, instead of the returned_job.name which is incorrect
example Below..... of the code and screen shot.....
![image](https://github.com/user-attachments/assets/abcfe992-9266-446a-8ea5-d0d13c643afd)

job_name = returned_job.name
job_name = 'cool_beard_rsghphcch0'

Repro steps:

**Comment by KhalidAlnujaidi** [comment]
Same issue, i think it has something to do with the signature, the model is actually not being logged.

There is a repeat in the columns, in addition to the output being Boolean when it is Integer maybe? Tried to remove duplicate column but it did not fix issue.
![image](https://github.com/user-attachments/assets/6719ddfd-2adc-4df4-baf5-9e273ecbaa7d)


Tried fixing code with following update, yes still did not work:
`
    # create the signature manually
    input_schema = Schema([
        ColSpec("integer", "Pregnancies"),
        ColSpec("integer", "PlasmaGlucose"),
        ColSpec("integer", "DiastolicBloodPressure"),
        ColSpec("integer", "TricepsThickness"),
        ColSpec("integer", "SerumInsulin"),
        ColSpec("double", "BMI"),
        ColSpec("double", "DiabetesPedigree"),
        ColSpec("integer", "Age"),
    ])

    output_schema = Schema([ColSpec("integer")])

    # Create the signature object
    signature = ModelSignature(inputs=input_schema, outputs=output_schema)
`

**Comment by afelix-95** [comment]
Thank you for pointing out this issue! It seems that `mlflow.autolog(log_models=False)` actually conflicts with `mlflow.sklearn.log_model(model, "model", signature=signature)` in the .py files, resulting in no logged models. For the last two scripts, the autolog command was removed so now the models should be logged as expected.
