### ISSUE TITLE
Lab 7: Link to Job Run does not resolve

### ISSUE THREAD

**Issue by jarougha** [MicrosoftLearning/mslearn-azure-ml#99]
# Module: 00
#### Step: 1: Open the Labs/07/Track model training with MLflow.ipynb notebook.

Description of issue
Link to Job Run does not resolve
Repro Steps
1. Goto --> Train and track models cell in the Track model training jupyter notebook, 
2. when clicking on the job links after the cell has run, the links do not resolve and result in this error:
![image](https://github.com/user-attachments/assets/302166ad-0bd7-44fa-8f89-08b866270d49)

Here is a screen shot also of the students cell after the job as run
![image](https://github.com/user-attachments/assets/17502514-a13c-4e2d-882f-368777a2287c)

**Comment by afelix-95** [comment]
It seems to be a product issue with Azure ML Studio. The job still runs successfully, only the link generated doesn't work. A note was added to the lab instructions explaining that if the link doesn't work, you can still review the job run in the **Jobs** section.
